# Generated by Django 4.2.5 on 2023-10-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_monster_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslandName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=30, unique=True)),
                ('portuguese_name', models.CharField(max_length=30, unique=True)),
                ('spanish_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='island',
            name='name_translations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.islandname'),
        ),
    ]
